config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ContentfulModel::Base
  self.content_type_id = 'recipe'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all.load
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "MarleySpoonCodingTest"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#" Recipe book by Marley Spoon
          .navbar-collapse.collapse.navbar-responsive-collapse

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      footer
        p &copy; Marley Spoon 2020

app/views/recipes/index.html.slim
h1 Recipes

table
  thead
    tr
      th
      th

  tbody
    - @recipes.each do |recipe|
      tr
        td = link_to image_tag(recipe.photo.url, size: '300x200'), recipe_path(recipe.id)
        td
          h4
            strong = link_to recipe.title, recipe_path(recipe.id)

app/views/recipes/show.html.slim
=< link_to 'Back', recipes_path

h3
  strong
    = @recipe.title
  - if @recipe.chef
    p4.chef = ' by ' + @recipe.chef.try(:name)
- if @recipe.tags
  p
    strong Tags: 
    = @recipe.tags.map(&:name).join(', ')
p
  text-monospace = @recipe.description
p
  = image_tag @recipe.photo.url

=< link_to 'Back', recipes_path